# Generated by scripts/homebrew/render-formula.sh in Dev916/mech-crate.
# Do not edit by hand: the tap-bump job in release.yml regenerates this file
# for every stable release.
class Mechcrate < Formula
  desc "CLI and MCP server for scaffolding projects and their infrastructure"
  homepage "https://mechcrate.dev"
  # macOS is the top-level url (universal binary, both architectures); brew
  # scans the version from it, so no explicit `version` stanza.
  url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.4/mx-v0.1.4-universal-apple-darwin.tar.gz"
  sha256 "cb8cef8aba549170a1efc5381bec1330831687b5f6483e2849b51ecd6e0c8faf"
  license any_of: ["Apache-2.0", "MIT"]

  on_linux do
    on_arm do
      url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.4/mx-v0.1.4-aarch64-unknown-linux-musl.tar.gz"
      sha256 "bae8be63f92b350d436ff29355bf82fba55fe3fc1f47fa76f488f6591d793115"
    end
    on_intel do
      url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.4/mx-v0.1.4-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bd6babca852a6792c862bc37b7f6a2b4db7d386d2e07c17a1e5ce0410e8cfdde"
    end
  end

  def install
    # The whole bundle goes into libexec so mech_crate_root() (which walks up
    # from the resolved executable looking for scripts/) lands on
    # Cellar/mechcrate/<version>/libexec, with templates/ and bin/lib/ beside the
    # binaries exactly as in the release layout. `mx self-update` sees the
    # Cellar path and delegates to `brew upgrade mechcrate`.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/mx", libexec/"bin/mx-mcp"
  end

  test do
    assert_match "mx 0.1.4", shell_output("#{bin}/mx --version")
  end
end
