# Generated by scripts/homebrew/render-formula.sh in Dev916/mech-crate.
# Do not edit by hand: the tap-bump job in release.yml regenerates this file
# for every stable release.
class Mechcrate < Formula
  desc "CLI and MCP server for scaffolding projects and their infrastructure"
  homepage "https://mechcrate.dev"
  # macOS is the top-level url (universal binary, both architectures); brew
  # scans the version from it, so no explicit `version` stanza.
  url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.3/mx-v0.1.3-universal-apple-darwin.tar.gz"
  sha256 "a6026343a4dbab8be6e060f524f567e7400166ae106bae988f57144883d6f0f5"
  license any_of: ["Apache-2.0", "MIT"]

  on_linux do
    on_arm do
      url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.3/mx-v0.1.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "000c59c4235f05dcdcad0bb58b2efdf02f59fe18f01e56e3fbcc4b97b376dd82"
    end
    on_intel do
      url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.3/mx-v0.1.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "0cae1186a1eaf7328106fb496bc8cb1e44867423d4502b323a8b230a83346a52"
    end
  end

  def install
    # The whole bundle goes into libexec so mech_crate_root() (which walks up
    # from the resolved executable looking for scripts/) lands on
    # Cellar/mechcrate/<version>/libexec, with templates/ and bin/lib/ beside the
    # binaries exactly as in the release layout. `mx self-update` sees the
    # Cellar path and delegates to `brew upgrade mechcrate`.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/mx", libexec/"bin/mx-mcp"
  end

  test do
    assert_match "mx 0.1.3", shell_output("#{bin}/mx --version")
  end
end
