# Generated by scripts/homebrew/render-formula.sh in Dev916/mech-crate.
# Do not edit by hand: the tap-bump job in release.yml regenerates this file
# for every stable release.
class Mx < Formula
  desc "MechCrate CLI and MCP server for project scaffolding and infrastructure"
  homepage "https://mechcrate.dev"
  version "0.1.2"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.2/mx-v0.1.2-universal-apple-darwin.tar.gz"
    sha256 "6ad47f4ffe7fc78ab8db100af5c29b6b60e3bae29f3e3e0790c93589f94757c4"
  end

  on_linux do
    on_arm do
      url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.2/mx-v0.1.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4cc39d70a5a77bef67ff260850fa2ae6931ba6744123cc39792431e21e8bdae8"
    end
    on_intel do
      url "https://github.com/unyform-ai/mech-crate-releases/releases/download/v0.1.2/mx-v0.1.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b80e8ae65fc9d98606b63856df86fcbfd21c9c889cf1cd4b864bbe213a2c147b"
    end
  end

  def install
    # The whole bundle goes into libexec so mech_crate_root() (which walks up
    # from the resolved executable looking for scripts/) lands on
    # Cellar/mx/<version>/libexec, with templates/ and bin/lib/ beside the
    # binaries exactly as in the release layout. `mx self-update` sees the
    # Cellar path and delegates to `brew upgrade mx`.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/mx", libexec/"bin/mx-mcp"
  end

  test do
    assert_match "mx 0.1.2", shell_output("#{bin}/mx --version")
  end
end
